import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import SmoothScroll from "./SmoothScroll";
import { ViewTransitions } from "next-view-transitions";
// import CustomEase from "gsap/CustomEase";
// import gsap from "gsap";
// gsap.registerPlugin(CustomEase);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ViewTransitions>
    <html lang="en">
      <body>
        <Nav />
        <SmoothScroll>
          {children}
        </SmoothScroll>
      </body>
    </html>
    </ViewTransitions>
  );
}
