import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/common/nav/Nav";
import SmoothScroll from "./SmoothScroll";
import { ViewTransitions } from "next-view-transitions";
// import CustomEase from "gsap/CustomEase";
// import gsap from "gsap";
// gsap.registerPlugin(CustomEase);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ViewTransitions>
    <html lang="en">
    <link
        rel="preload"
        href="fonts/NeueHaasGrotText-55Roman.otf"
        as="font"
        type="font/otf"
        crossOrigin="anonymous"
      />
    <link
        rel="preload"
        href="fonts/NeueHaasGrotText-65Medium.otf"
        as="font"
        type="font/otf"
        crossOrigin="anonymous"
      />
    <link
        rel="preload"
        href="fonts/NeueHaasGrotText-75Bold.otf"
        as="font"
        type="font/otf"
        crossOrigin="anonymous"
      />
      <body>
      <script dangerouslySetInnerHTML={{ __html: `history.scrollRestoration = "manual"` }} />
        <Nav />
        <SmoothScroll>
          <div data-gsap="page">
            {children}
          </div>
        </SmoothScroll>
      </body>
    </html>
    </ViewTransitions>
  );
}
